// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKQMOLOxnWSozqzPhbxqODBQidSxOMFg',
    appId: '1:21095599679:web:3a0bde537704bc4101b28a',
    messagingSenderId: '21095599679',
    projectId: 'ricardo-7f01b',
    authDomain: 'ricardo-7f01b.firebaseapp.com',
    storageBucket: 'ricardo-7f01b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy5L5h4VlSvv0cj70XtUguGo83IM1A49s',
    appId: '1:21095599679:android:309c16ff99ff266801b28a',
    messagingSenderId: '21095599679',
    projectId: 'ricardo-7f01b',
    storageBucket: 'ricardo-7f01b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa1ODQZgjP9J7S7eqQPJzGVsrz91Hgptg',
    appId: '1:21095599679:ios:4a4d68f2d096f25901b28a',
    messagingSenderId: '21095599679',
    projectId: 'ricardo-7f01b',
    storageBucket: 'ricardo-7f01b.firebasestorage.app',
    iosBundleId: 'com.gogodriver.gogodriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa1ODQZgjP9J7S7eqQPJzGVsrz91Hgptg',
    appId: '1:21095599679:ios:4a4d68f2d096f25901b28a',
    messagingSenderId: '21095599679',
    projectId: 'ricardo-7f01b',
    storageBucket: 'ricardo-7f01b.firebasestorage.app',
    iosBundleId: 'com.gogodriver.gogodriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFKQMOLOxnWSozqzPhbxqODBQidSxOMFg',
    appId: '1:21095599679:web:515a2c641eca4a5001b28a',
    messagingSenderId: '21095599679',
    projectId: 'ricardo-7f01b',
    authDomain: 'ricardo-7f01b.firebaseapp.com',
    storageBucket: 'ricardo-7f01b.firebasestorage.app',
  );
}
